# Generated by Django 4.2.3 on 2023-07-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='images_path',
        ),
        migrations.AddField(
            model_name='tweet',
            name='image',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
