# Generated by Django 4.2.3 on 2023-07-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_tweet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='comments',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='likes',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='retweets',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='vues',
            field=models.JSONField(default=None),
        ),
    ]
